// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;

    // ✅ NEW: graceful fallback so app doesn't crash on linux builds
    // If you truly don't support linux, you can keep throw instead.
      case TargetPlatform.linux:
        return web;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0NpQ-aQoaEzKEYNSUAMcbp_Z-lZwPMbg',
    appId: '1:594884039526:web:6036f0b2d04a074a72eea7',
    messagingSenderId: '594884039526',
    projectId: 'feng497app',
    authDomain: 'feng497app.firebaseapp.com',
    storageBucket: 'feng497app.firebasestorage.app',
    measurementId: 'G-H0GVG7K682',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsnlv0QSU8Wb2rPuFM-O_2IhdruH9q6OA',
    appId: '1:594884039526:android:91b0385de72233d372eea7',
    messagingSenderId: '594884039526',
    projectId: 'feng497app',
    storageBucket: 'feng497app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJAA7xYwwOnbpmzTzJkhrPzfwcmJ0O1I',
    appId: '1:594884039526:ios:29f50ac201a185cf72eea7',
    messagingSenderId: '594884039526',
    projectId: 'feng497app',
    storageBucket: 'feng497app.firebasestorage.app',
    iosBundleId: 'com.example.feng497App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJAA7xYwwOnbpmzTzJkhrPzfwcmJ0O1I',
    appId: '1:594884039526:ios:29f50ac201a185cf72eea7',
    messagingSenderId: '594884039526',
    projectId: 'feng497app',
    storageBucket: 'feng497app.firebasestorage.app',
    iosBundleId: 'com.example.feng497App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0NpQ-aQoaEzKEYNSUAMcbp_Z-lZwPMbg',
    appId: '1:594884039526:web:9708954e91b5894b72eea7',
    messagingSenderId: '594884039526',
    projectId: 'feng497app',
    authDomain: 'feng497app.firebaseapp.com',
    storageBucket: 'feng497app.firebasestorage.app',
    measurementId: 'G-R8689R6HC7',
  );
}
